import imgHouse1 from '../public/images/house-1.png';
import imgHouse2 from '../public/images/house-2.png';
import imgHouse3 from '../public/images/house-3.png';
import imgHouse4 from '../public/images/house-4.png';
import imgHouse5 from '../public/images/house-5.png';
import imgHouse6 from '../public/images/house-6.png';
import imgHouse7 from '../public/images/house-7.png';
import imgHouse8 from '../public/images/house-8.png';
import imgHouse9 from '../public/images/house-9.png';
import imgHouse10 from '../public/images/house-10.png';
import imgHouse11 from '../public/images/house-11.png';
import imgHouse12 from '../public/images/house-12.png';

const listing = [
  {
    id: 1,
    title: 'Ataz Standard House',
    slug: 'ataz-standard-house',
    price: '$2,800',
    address: 'Pluto Street',
    country: 'Indonesia',
    beds: '1',
    baths: '2',
    area: '800',
    image: imgHouse1,
    description: '',
    status: 'active',
    featured: true,
  },
  {
    id: 2,
    title: 'Qiri Minimalist House',
    slug: 'qiri-minimalist-house',
    price: '$4,800',
    address: 'Jupiter Street',
    country: 'Indonesia',
    beds: '1',
    baths: '3',
    area: '1,800',
    image: imgHouse2,
    description: '',
    status: 'active',
    featured: true,
  },
  {
    id: 3,
    title: 'Qanan Luxury House',
    slug: 'qanan-luxury-house',
    price: '$6,800',
    address: 'Mars Street',
    country: 'Indonesia',
    beds: '3',
    baths: '4',
    area: '2,800',
    image: imgHouse3,
    description: '',
    status: 'active',
    featured: true,
  },
  {
    id: 4,
    title: 'Tingah Elegant House',
    slug: 'tingah-elegant-house',
    price: '$8,800',
    address: 'Maple Avenue',
    country: 'Indonesia',
    beds: '4',
    baths: '5',
    area: '3,800',
    image: imgHouse4,
    description: '',
    status: 'active',
    featured: true,
  },
  {
    id: 5,
    title: 'Nsor Standard House',
    slug: 'nsor-standard-house',
    price: '$7,500',
    address: 'Pine Street',
    country: 'Indonesia',
    beds: '3',
    baths: '4',
    area: '2,700',
    image: imgHouse5,
    description: '',
    status: 'active',
    featured: false,
  },
  {
    id: 6,
    title: 'Qiwo Minimalist House',
    slug: 'qiwo-minimalist-house',
    price: '$4,800',
    address: 'Willow Way',
    country: 'Indonesia',
    beds: '2',
    baths: '3',
    area: '1,700',
    image: imgHouse6,
    description: '',
    status: 'active',
    featured: false,
  },
  {
    id: 7,
    title: 'Tengen Luxury House',
    slug: 'tengen-luxury-house',
    price: '$6,600',
    address: 'Cedar Lane',
    country: 'Indonesia',
    beds: '3',
    baths: '4',
    area: '2,600',
    image: imgHouse7,
    description: '',
    status: 'active',
    featured: false,
  },
  {
    id: 8,
    title: 'Tngah Elegant House',
    slug: 'tngah-elegant-house',
    price: '$5,600',
    address: 'Birch Road',
    country: 'Indonesia',
    beds: '3',
    baths: '4',
    area: '2,400',
    image: imgHouse8,
    description: '',
    status: 'active',
    featured: false,
  },
  {
    id: 9,
    title: 'Ndukur Standard House',
    slug: 'ndukur-standard-house',
    price: '$9,600',
    address: 'Dogwood Drive',
    country: 'Indonesia',
    beds: '5',
    baths: '6',
    area: '4,400',
    image: imgHouse9,
    description: '',
    status: 'active',
    featured: false,
  },
  {
    id: 10,
    title: 'Kenen Minimalist House',
    slug: 'kenen-minimalist-house',
    price: '$4,800',
    address: 'Dogwood Drive',
    country: 'Indonesia',
    beds: '2',
    baths: '3',
    area: '1,900',
    image: imgHouse10,
    description: '',
    status: 'active',
    featured: false,
  },
  {
    id: 11,
    title: 'Kiro Luxury House',
    slug: 'kiro-luxury-house',
    price: '$7,800',
    address: 'Hazelwood Drive',
    country: 'Indonesia',
    beds: '3',
    baths: '4',
    area: '3,000',
    image: imgHouse11,
    description: '',
    status: 'active',
    featured: false,
  },
  {
    id: 12,
    title: 'Muter Elegant House',
    slug: 'muter-elegant-house',
    price: '$7,800',
    address: 'Hazelwood Drive',
    country: 'Indonesia',
    beds: '3',
    baths: '4',
    area: '3,000',
    image: imgHouse12,
    description: '',
    status: 'active',
    featured: false,
  },
];

export default listing;