// import { Lora, Nunito } from '@next/font/google';
import Head from 'next/head';
import Layout from '../components/Layout';
import '../styles/globals.css'

// const lora = Lora({
//   subsets: ['latin'],
// });

// const nunito = Nunito({
//   subsets: ['latin'],
// });

function MyApp({ Component, pageProps }) {
  return (
    <>
      {/* <style jsx global>
        {`
          :root {
            --lora-font: ${lora.style.fontFamily};
            --nunito-font: ${nunito.style.fontFamily};
          }
        `}
      </style> */}
      <Head>
        <title>Real Estate</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <Component {...pageProps} />
      </Layout>
    </>
  );
}

export default MyApp
